import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-students-list',
  templateUrl: './students-list.component.html',
  styleUrls: ['./students-list.component.scss']
})
export class StudentsListComponent implements OnInit {

  headers = ["ID", "Nombre", "Apellido", "Correo"];
  estudiante =[
    {nombre: 'Daniel', 
    apellido: 'Janco', 
    correo: '201800140@est.umss.edu'},
    {nombre: 'Pablo', 
    apellido: 'Zelada', 
    correo: '201800141@est.umss.edu'},
    {nombre: 'Diego', 
    apellido: 'Chavez', 
    correo: '201800142@est.umss.edu'},
    {nombre: 'Andres', 
    apellido: 'Tapia', 
    correo: '201800143@est.umss.edu'},
    {nombre: 'Luis', 
    apellido: 'Quiroz', 
    correo: '201800144@est.umss.edu'},
    {nombre: 'Daniel', 
    apellido: 'Janco', 
    correo: '201800140@est.umss.edu'},
    {nombre: 'Pablo', 
    apellido: 'Zelada', 
    correo: '201800141@est.umss.edu'},
    {nombre: 'Diego', 
    apellido: 'Chavez', 
    correo: '201800142@est.umss.edu'},
    {nombre: 'Andres', 
    apellido: 'Tapia', 
    correo: '201800143@est.umss.edu'},
    {nombre: 'Luis', 
    apellido: 'Quiroz', 
    correo: '201800144@est.umss.edu'},
    {nombre: 'Daniel', 
    apellido: 'Janco', 
    correo: '201800140@est.umss.edu'},
    {nombre: 'Pablo', 
    apellido: 'Zelada', 
    correo: '201800141@est.umss.edu'},
    {nombre: 'Diego', 
    apellido: 'Chavez', 
    correo: '201800142@est.umss.edu'},
    {nombre: 'Andres', 
    apellido: 'Tapia', 
    correo: '201800143@est.umss.edu'},
    {nombre: 'Luis', 
    apellido: 'Quiroz', 
    correo: '201800144@est.umss.edu'},
    {nombre: 'Daniel', 
    apellido: 'Janco', 
    correo: '201800140@est.umss.edu'},
    {nombre: 'Pablo', 
    apellido: 'Zelada', 
    correo: '201800141@est.umss.edu'},
    {nombre: 'Diego', 
    apellido: 'Chavez', 
    correo: '201800142@est.umss.edu'},
    {nombre: 'Andres', 
    apellido: 'Tapia', 
    correo: '201800143@est.umss.edu'},
    {nombre: 'Luis', 
    apellido: 'Quiroz', 
    correo: '201800144@est.umss.edu'},
    {nombre: 'Daniel', 
    apellido: 'Janco', 
    correo: '201800140@est.umss.edu'},
    {nombre: 'Pablo', 
    apellido: 'Zelada', 
    correo: '201800141@est.umss.edu'},
    {nombre: 'Diego', 
    apellido: 'Chavez', 
    correo: '201800142@est.umss.edu'},
    {nombre: 'Andres', 
    apellido: 'Tapia', 
    correo: '201800143@est.umss.edu'},
    {nombre: 'Luis', 
    apellido: 'Quiroz', 
    correo: '201800144@est.umss.edu'},
    {nombre: 'Daniel', 
    apellido: 'Janco', 
    correo: '201800140@est.umss.edu'},
    {nombre: 'Pablo', 
    apellido: 'Zelada', 
    correo: '201800141@est.umss.edu'},
    {nombre: 'Diego', 
    apellido: 'Chavez', 
    correo: '201800142@est.umss.edu'},
    {nombre: 'Andres', 
    apellido: 'Tapia', 
    correo: '201800143@est.umss.edu'},
    {nombre: 'Luis', 
    apellido: 'Quiroz', 
    correo: '201800144@est.umss.edu'}
  ]
  constructor() { }

  ngOnInit(): void {
  }

}
